services:
  password-service:
    restart: always
    build:
      context: ./backend/password-service
      dockerfile: Dockerfile
    ports:
      - 3001:8080
    deploy:
      resources:
        limits:
          memory: 80M
  ddns-ip-service:
    restart: always
    build:
      context: ./backend/ddns-ip-service
      dockerfile: Dockerfile
    ports:
      - 3002:8080
    deploy:
      resources:
        limits:
          memory: 80M

  record-service:
    restart: always
    build:
      context: ./backend/record-service
      dockerfile: Dockerfile
    ports:
      - 3000:8080
    deploy:
      resources:
        limits:
          memory: 80M
  
  database:
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: defaultdnsupdaterpassword
      POSTGRES_USER: dnsupdater
    ports:
      - 5432:5432